// postinstall/pre* 前置腳本,補齊「clone 之後、第一次跑起來之前」缺的兩個檔案。
// 兩者都是 gitignored(一個含 secret、一個是產生物),所以新 clone 一定沒有,
// 而沒有它們的失敗都不會指回這裡:
//
//   .dev.vars            缺 SECRETS_KEY → 直到「存第一個加密設定」才 throw,
//                        新手不會把那個錯誤連回 quickstart。
//   cloudflare-env.d.ts  缺 → src/lib/cf.ts 依賴的全域型別不存在,
//                        typecheck / lint 直接紅,但 next dev 照樣跑,更難聯想。
//   .open-next/worker.d.ts
//                        缺 → `next build` 的 type-check 在 custom-worker.ts 紅,
//                        而它 import 的正是 opennext build 稍後才產出的檔案。
//                        新 clone 因此 100% build 不出來(見下方該段註解)。
//
// 同 ensure-licensing-stub.mjs 的哲學:只在檔案缺席時寫,已存在就完全不動。
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// ---- .dev.vars ----------------------------------------------------------
// 逐「鍵」補齊,而不是「檔案存在就跳過」。後者的後果是:任何在這個清單新增
// secret 的改動,對所有既有 clone 都不生效 —— 他們的 .dev.vars 早就存在了,
// 於是本機直接壞掉,而錯誤訊息只會說某個 env 不見了。
const devVars = join(root, ".dev.vars");

// 開發用的值當場產生,不放固定範例值(範例檔裡放一把固定金鑰是反模式)。
// 這些只用於本機;production 一律走 `wrangler secret put <NAME>`。
const DEV_SECRETS = [
  {
    key: "SECRETS_KEY",
    note: "AES-GCM 金鑰(32-byte base64)。換掉會讓既存的加密設定變成亂碼,信封沒有 key id。",
  },
  {
    key: "AUTH_PEPPER",
    note: "密碼進 PBKDF2 之前先做 HMAC。設了之後不能拔掉,否則既有密碼全部算不出來。",
  },
  {
    key: "SETUP_TOKEN",
    note: "/setup 的 bootstrap 憑證。沒有它就不能建第一個管理員(刻意 fail-closed)。",
  },
];

const existing = existsSync(devVars) ? readFileSync(devVars, "utf8") : null;
if (existing === null) {
  writeFileSync(
    devVars,
    [
      "# AUTO-GENERATED by scripts/ensure-dev-env.mjs — 本機開發用,已被 .gitignore 排除。",
      "# production 的值一律用 `wrangler secret put <NAME>` 另外設定,絕不沿用這裡的。",
      "NEXTJS_ENV=development",
      "",
      ...DEV_SECRETS.flatMap(({ key, note }) => [
        `# ${note}`,
        `${key}=${randomBytes(32).toString("base64")}`,
        "",
      ]),
    ].join("\n"),
    { mode: 0o600 },
  );
  console.log(
    `[dev-env] .dev.vars 不存在 —— 已產生,內含 ${DEV_SECRETS.map((s) => s.key).join(" / ")}。`,
  );
} else {
  // 只補缺的,絕不覆寫既有的值(覆寫 SECRETS_KEY = 本機既存的加密設定全毀)。
  const missing = DEV_SECRETS.filter(
    ({ key }) => !new RegExp(`^\\s*${key}\\s*=`, "m").test(existing),
  );
  if (missing.length > 0) {
    appendFileSync(
      devVars,
      [
        existing.endsWith("\n") ? "" : "\n",
        ...missing.flatMap(({ key, note }) => [
          `# ${note}`,
          `${key}=${randomBytes(32).toString("base64")}`,
          "",
        ]),
      ].join("\n"),
    );
    console.log(
      `[dev-env] .dev.vars 缺少 ${missing.map((s) => s.key).join(" / ")} —— 已補上。`,
    );
  }
}

// ---- cloudflare-env.d.ts ------------------------------------------------
// `wrangler types` 純粹讀 wrangler.jsonc 產生型別,不需要網路也不需要登入。
// 但它仍可能因為 wrangler 版本/設定問題失敗 —— 失敗一律不阻斷安裝,只提示。
const envTypes = join(root, "cloudflare-env.d.ts");
if (!existsSync(envTypes)) {
  try {
    execFileSync(
      "npx",
      ["wrangler", "types", "--env-interface", "CloudflareEnv", "cloudflare-env.d.ts"],
      // Windows 上 npx 是 npx.cmd,execFile 不透過 shell 會找不到。失敗本來就不致命,
      // 但沒必要讓整個平台都走到那條 warn 分支。
      { cwd: root, stdio: "pipe", shell: process.platform === "win32" },
    );
    console.log("[dev-env] cloudflare-env.d.ts 不存在 —— 已由 `wrangler types` 產生。");
  } catch {
    console.warn(
      "[dev-env] 無法自動產生 cloudflare-env.d.ts。請手動執行 `pnpm cf-typegen`;" +
        "在那之前 typecheck 與 lint 會因缺少 CloudflareEnv 型別而失敗。",
    );
  }
}

// ---- .open-next/worker.d.ts ---------------------------------------------
// 雞生蛋:custom-worker.ts(wrangler 的 `main`)import `./.open-next/worker.js`,
// 但那是 `opennextjs-cloudflare build` 的產出物 —— 而它的第一步就是 `next build`。
// 於是全新 clone 必定卡在 type-check:產出物要 build 才有,build 又要它才過。
//
// 不能改用 tsconfig `exclude` 迴避:cloudflare-env.d.ts 會 `import "./custom-worker"`,
// 被 import 的檔案 TS 一律納入,exclude 管不到(tsc --explainFiles 可複現)。
//
// 所以在 type-check 前補一份**只有型別、沒有實作**的 stub。真正的 build 會用實作
// 覆蓋整個目錄;實作一旦存在就不再寫 stub,避免它反過來蓋掉真實型別。
const openNextDir = join(root, ".open-next");
const openNextWorker = join(openNextDir, "worker.js");
const openNextTypes = join(openNextDir, "worker.d.ts");
if (!existsSync(openNextWorker) && !existsSync(openNextTypes)) {
  mkdirSync(openNextDir, { recursive: true });
  writeFileSync(
    openNextTypes,
    [
      "// 由 scripts/ensure-dev-env.mjs 產生的佔位型別,只為了讓第一次 build 的",
      "// type-check 過得去。`opennextjs-cloudflare build` 會用真正的產出物覆蓋。",
      "declare const handler: {",
      "  fetch(",
      "    request: Request,",
      "    env: CloudflareEnv,",
      "    ctx: ExecutionContext,",
      "  ): Response | Promise<Response>;",
      "};",
      "export default handler;",
      "",
    ].join("\n"),
  );
  console.log(
    "[dev-env] .open-next/ 尚無產出物 —— 已放置 worker.d.ts 佔位型別供首次 build 使用。",
  );
}
