// postinstall/pre* 前置腳本,補齊「clone 之後、第一次跑起來之前」缺的兩個檔案。
// 兩者都是 gitignored(一個含 secret、一個是產生物),所以新 clone 一定沒有,
// 而沒有它們的失敗都不會指回這裡:
//
//   .dev.vars            缺 SECRETS_KEY → 直到「存第一個加密設定」才 throw,
//                        新手不會把那個錯誤連回 quickstart。
//   cloudflare-env.d.ts  缺 → src/lib/cf.ts 依賴的全域型別不存在,
//                        typecheck / lint 直接紅,但 next dev 照樣跑,更難聯想。
//   .open-next/worker.d.ts
//                        缺 → `next build` 的 type-check 在 custom-worker.ts 紅,
//                        而它 import 的正是 opennext build 稍後才產出的檔案。
//                        新 clone 因此 100% build 不出來(見下方該段註解)。
//
// 同 ensure-licensing-stub.mjs 的哲學:只在檔案缺席時寫,已存在就完全不動。
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// ---- .dev.vars ----------------------------------------------------------
const devVars = join(root, ".dev.vars");
if (!existsSync(devVars)) {
  // 開發用金鑰當場產生,而不是要使用者自己跑 openssl —— 少一個手動步驟,
  // 且保證每個 clone 拿到的是不同的值(範例檔裡放一把固定金鑰是反模式)。
  // 這把金鑰只用於本機 D1;production 走 `wrangler secret put SECRETS_KEY`。
  writeFileSync(
    devVars,
    [
      "# AUTO-GENERATED by scripts/ensure-dev-env.mjs — 本機開發用,已被 .gitignore 排除。",
      "# production 的金鑰請用 `wrangler secret put SECRETS_KEY` 另外設定,絕不沿用此值",
      "# (換 SECRETS_KEY 會讓所有既存的加密設定變成亂碼,信封沒有 key id,無漸進遷移路徑)。",
      "NEXTJS_ENV=development",
      `SECRETS_KEY=${randomBytes(32).toString("base64")}`,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );
  console.log("[dev-env] .dev.vars 不存在 —— 已產生,內含新的開發用 SECRETS_KEY。");
}

// ---- cloudflare-env.d.ts ------------------------------------------------
// `wrangler types` 純粹讀 wrangler.jsonc 產生型別,不需要網路也不需要登入。
// 但它仍可能因為 wrangler 版本/設定問題失敗 —— 失敗一律不阻斷安裝,只提示。
const envTypes = join(root, "cloudflare-env.d.ts");
if (!existsSync(envTypes)) {
  try {
    execFileSync(
      "npx",
      ["wrangler", "types", "--env-interface", "CloudflareEnv", "cloudflare-env.d.ts"],
      // Windows 上 npx 是 npx.cmd,execFile 不透過 shell 會找不到。失敗本來就不致命,
      // 但沒必要讓整個平台都走到那條 warn 分支。
      { cwd: root, stdio: "pipe", shell: process.platform === "win32" },
    );
    console.log("[dev-env] cloudflare-env.d.ts 不存在 —— 已由 `wrangler types` 產生。");
  } catch {
    console.warn(
      "[dev-env] 無法自動產生 cloudflare-env.d.ts。請手動執行 `pnpm cf-typegen`;" +
        "在那之前 typecheck 與 lint 會因缺少 CloudflareEnv 型別而失敗。",
    );
  }
}

// ---- .open-next/worker.d.ts ---------------------------------------------
// 雞生蛋:custom-worker.ts(wrangler 的 `main`)import `./.open-next/worker.js`,
// 但那是 `opennextjs-cloudflare build` 的產出物 —— 而它的第一步就是 `next build`。
// 於是全新 clone 必定卡在 type-check:產出物要 build 才有,build 又要它才過。
//
// 不能改用 tsconfig `exclude` 迴避:cloudflare-env.d.ts 會 `import "./custom-worker"`,
// 被 import 的檔案 TS 一律納入,exclude 管不到(tsc --explainFiles 可複現)。
//
// 所以在 type-check 前補一份**只有型別、沒有實作**的 stub。真正的 build 會用實作
// 覆蓋整個目錄;實作一旦存在就不再寫 stub,避免它反過來蓋掉真實型別。
const openNextDir = join(root, ".open-next");
const openNextWorker = join(openNextDir, "worker.js");
const openNextTypes = join(openNextDir, "worker.d.ts");
if (!existsSync(openNextWorker) && !existsSync(openNextTypes)) {
  mkdirSync(openNextDir, { recursive: true });
  writeFileSync(
    openNextTypes,
    [
      "// 由 scripts/ensure-dev-env.mjs 產生的佔位型別,只為了讓第一次 build 的",
      "// type-check 過得去。`opennextjs-cloudflare build` 會用真正的產出物覆蓋。",
      "declare const handler: {",
      "  fetch(",
      "    request: Request,",
      "    env: CloudflareEnv,",
      "    ctx: ExecutionContext,",
      "  ): Response | Promise<Response>;",
      "};",
      "export default handler;",
      "",
    ].join("\n"),
  );
  console.log(
    "[dev-env] .open-next/ 尚無產出物 —— 已放置 worker.d.ts 佔位型別供首次 build 使用。",
  );
}
