// .dev.vars 的逐鍵更新 —— secret 值在本機的唯一落點。
//
// 為什麼是這裡而不是 wrangler.jsonc:.dev.vars 已被 .gitignore 排除(見 repo 根的
// .gitignore),而 wrangler.jsonc 會進版控。cms 是公開 repo,把 secret 寫進設定檔
// 等於直接推上 GitHub。
//
// 為什麼不順手 `wrangler secret put`:`add` 執行的當下,使用者很可能還沒 `wrangler
// login`、Worker 也還沒 deploy(帳號上根本沒有東西可以掛 secret)。所以這支 CLI
// 只印指令,由使用者在 deploy 之後自己跑。
//
// 更新策略沿用 scripts/ensure-dev-env.mjs:逐「鍵」處理,不是「檔案存在就跳過」。
// 差別在這裡的值是使用者剛剛親手輸入的,所以同鍵**會**覆寫(那正是他的意圖),
// 而不像 ensure-dev-env 那樣只補缺 —— 那邊補的是隨機開發金鑰,覆寫會毀掉本機資料。

import { readFile, writeFile } from "node:fs/promises";

/** 需要引號的值:含空白、`#`、引號、反斜線,或本身是空的。 */
const BARE_SAFE_RE = /^[^\s#"'\\]+$/;

export function formatDevVarValue(value: string): string {
  // dotenv 的雙引號形式支援跳脫;JSON.stringify 產出的正好是同一種寫法。
  return BARE_SAFE_RE.test(value) ? value : JSON.stringify(value);
}

const HEADER = [
  "# AUTO-GENERATED by sz-ws-cms — 本機開發用,已被 .gitignore 排除。",
  "# production 的值一律用 `wrangler secret put <NAME>` 另外設定,絕不沿用這裡的。",
];

export interface DevVarsWriteResult {
  text: string;
  /** 真的被寫入或更新的鍵(值已經一樣的不列)。 */
  changed: string[];
}

/**
 * 把 entries 併進既有內容。`existing` 為 null 代表檔案還不存在。
 * 註解與其他鍵原樣保留;同鍵就地取代那一行,不會在檔尾堆出第二份。
 */
export function upsertDevVars(
  existing: string | null,
  entries: ReadonlyMap<string, string>,
): DevVarsWriteResult {
  const lines = existing === null ? [...HEADER, ""] : existing.split("\n");
  const changed: string[] = [];

  for (const [key, rawValue] of entries) {
    const line = `${key}=${formatDevVarValue(rawValue)}`;
    const at = lines.findIndex((l) => new RegExp(`^\\s*${escapeRe(key)}\\s*=`).test(l));
    if (at >= 0) {
      if (lines[at] === line) continue; // 完全一樣 → 不動
      lines[at] = line;
      changed.push(key);
      continue;
    }
    // 附加在檔尾。維持「一鍵一行、鍵之間空一行」的既有排版。
    if (lines.length > 0 && lines[lines.length - 1].trim() !== "") lines.push("");
    lines.push(line, "");
    changed.push(key);
  }

  return { text: lines.join("\n"), changed };
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * 讀 → 併 → 寫。權限固定 0600(檔案內容是 secret,不該給同機器其他使用者讀)。
 * 沒有任何變更時完全不寫檔。
 */
export async function persistDevVars(
  filePath: string,
  entries: ReadonlyMap<string, string>,
): Promise<string[]> {
  if (entries.size === 0) return [];
  let existing: string | null = null;
  try {
    existing = await readFile(filePath, "utf8");
  } catch {
    existing = null;
  }
  const { text, changed } = upsertDevVars(existing, entries);
  if (changed.length === 0) return [];
  await writeFile(filePath, text, { encoding: "utf8", mode: 0o600 });
  return changed;
}
