import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { formatDevVarValue, persistDevVars, upsertDevVars } from "./devvars.js";

let dir: string;
let file: string;

beforeEach(async () => {
  dir = await mkdtemp(path.join(tmpdir(), "szws-devvars-"));
  file = path.join(dir, ".dev.vars");
});
afterEach(async () => {
  await rm(dir, { recursive: true, force: true });
});

describe("formatDevVarValue", () => {
  it("單純的值不加引號", () => {
    expect(formatDevVarValue("abc123")).toBe("abc123");
  });

  it("含空白 / # / 引號的值加雙引號並跳脫", () => {
    expect(formatDevVarValue("a b")).toBe('"a b"');
    expect(formatDevVarValue("x#y")).toBe('"x#y"');
    expect(formatDevVarValue('say "hi"')).toBe('"say \\"hi\\""');
    expect(formatDevVarValue("line1\nline2")).toBe('"line1\\nline2"');
  });

  it("空值也加引號(裸的 KEY= 會被讀成不同的東西)", () => {
    expect(formatDevVarValue("")).toBe('""');
  });
});

describe("upsertDevVars", () => {
  it("檔案不存在時帶上說明檔頭", () => {
    const { text, changed } = upsertDevVars(null, new Map([["EXT_A_TOKEN", "t"]]));
    expect(text).toContain("AUTO-GENERATED by sz-ws-cms");
    expect(text).toContain("EXT_A_TOKEN=t");
    expect(changed).toEqual(["EXT_A_TOKEN"]);
  });

  it("同鍵就地取代,不會在檔尾堆出第二份", () => {
    const before = "SECRETS_KEY=keep-me\nEXT_A_TOKEN=old\n";
    const { text, changed } = upsertDevVars(before, new Map([["EXT_A_TOKEN", "new"]]));
    expect(text).toContain("SECRETS_KEY=keep-me");
    expect(text).toContain("EXT_A_TOKEN=new");
    expect(text).not.toContain("old");
    expect(text.match(/EXT_A_TOKEN=/g)).toHaveLength(1);
    expect(changed).toEqual(["EXT_A_TOKEN"]);
  });

  it("既有的其他鍵與註解原樣保留", () => {
    const before = "# 這行是註解\nAUTH_PEPPER=abc\n";
    const { text } = upsertDevVars(before, new Map([["EXT_B_KEY", "v"]]));
    expect(text).toContain("# 這行是註解");
    expect(text).toContain("AUTH_PEPPER=abc");
    expect(text).toContain("EXT_B_KEY=v");
  });

  it("值完全一樣時不算變更(冪等)", () => {
    const before = "EXT_A_TOKEN=t\n";
    const { changed } = upsertDevVars(before, new Map([["EXT_A_TOKEN", "t"]]));
    expect(changed).toEqual([]);
  });
});

describe("persistDevVars", () => {
  it("沒有變更就完全不寫檔", async () => {
    await writeFile(file, "EXT_A_TOKEN=t\n", "utf8");
    const before = await stat(file);
    await new Promise((r) => setTimeout(r, 10));
    await expect(persistDevVars(file, new Map([["EXT_A_TOKEN", "t"]]))).resolves.toEqual([]);
    expect((await stat(file)).mtimeMs).toBe(before.mtimeMs);
  });

  it("新建的檔案權限是 0600(內容是 secret,不給同機器其他人讀)", async () => {
    await persistDevVars(file, new Map([["EXT_A_TOKEN", "t"]]));
    expect((await stat(file)).mode & 0o777).toBe(0o600);
    expect(await readFile(file, "utf8")).toContain("EXT_A_TOKEN=t");
  });

  it("空的 entries 不會建出檔案", async () => {
    await expect(persistDevVars(file, new Map())).resolves.toEqual([]);
    await expect(stat(file)).rejects.toThrow();
  });
});
